build: use Golang 1.17 when building the bundle container-image
When the GitHub Worflow to push the bundle container-image runs, it uses
the standard version of Go that is installed on the Ubuntu worker. This
version does not work while building `kustomize`:

    go build -o /home/runner/work/kubernetes-csi-addons/kubernetes-csi-addons/bin/kustomize ./vendor/sigs.k8s.io/kustomize/kustomize/v4
    # sigs.k8s.io/kustomize/kyaml/filesys
    vendor/sigs.k8s.io/kustomize/kyaml/filesys/fsondisk.go:115:21: undefined: os.ReadDir

The project requires Go 1.17, so we should use that while building the
bundle container-image as well.

Signed-off-by: Niels de Vos <ndevos@redhat.com>